### ISSUE TITLE
Java exception due to postgresql with release 0.1

### ISSUE THREAD

**Issue by joelguittet** [taptap/sonarqube-badges#2]
Hello,

Great job done here, not a bad idea to have the badges for private projects !

I'm trying to get it working, currently I have configure a test repository and sonarqube server.

When getting the badge (`http://127.0.0.1:8080/api/project_badges/measure?project=test-pjt&metric=alert_status` for example), I have an error and a Java exception.

Extract below:

```
2021-12-08 18:58:05.086 ERROR 7 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: column "user_managed" does not exist
  Position: 100
### The error may exist in com/github/taptap/sonarqubebadges/entity/Metric$Mapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  uuid,name AS kee,short_name,val_type AS valueType,description,domain,direction,qualitative,user_managed,worst_value,best_value,optimized_best_value,hidden,delete_historical_data,enabled,decimal_scale  FROM metrics     WHERE (name = ?)
### Cause: org.postgresql.util.PSQLException: ERROR: column "user_managed" does not exist
  Position: 100
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "user_managed" does not exist
  Position: 100] with root cause

org.postgresql.util.PSQLException: ERROR: column "user_managed" does not exist
```

I guess you are using a specific sonarqube version ? What is the compatibility of your app with sonarqube ?

My config is sonarqube community 9.1 + postgresql 14 actually.

Regards,
Joel

**Comment by klboke** [comment]
Hello, Joel

Your guess is probably right, as I don't have your sonarqube version environment, so it's not convenient to test it. It looks like this field is not involved in calculating the badge, so I'll try to remove this field and then you can try it in

**Comment by klboke** [comment]
You can try with this version: https://github.com/taptap/sonarqube-badges/releases/download/v0.3/sonarqube-badges-0.3.tar

Looking forward to your good news!

**Comment by joelguittet** [comment]
Hello @klboke 

Thanks for the very quick reply to this issue. The 0.3 release is working like a charm in my Sonarqube 9.1 community environment.

For your information, I have pushed a docker image at https://hub.docker.com/repository/docker/joelguittet/sonarqube-badges/general.
If you want to copy the Dockerfile it's ok for me of course, but the approach is a bit different than the one you provide so... I let you check and take if you want it.
I have personally setup this on my Synology NAS with sonarqube+postgresl+badges all together with nginx to have HTTPS. Badges are now displayed on my gitlab container which is also hosted on my NAS.
Very cool :-)

Thanks again for this app and for your support to this issue!

Regards
Joel
